:uri-qg-status: https://sonarcloud.io/project/overview?id=Chawotto_MorrS
:img-qg-status: https://sonarcloud.io/api/project_badges/measure?project=Chawotto_MorrS&metric=alert_status
:uri-build-status: https://github.com/Chawotto/MorrS/actions/workflows/build.yml
:img-build-status: https://github.com/Chawotto/MorrS/actions/workflows/build.yml/badge.svg

image:{img-build-status}[Build Status, link={uri-build-status}]
image:{img-qg-status}[Quality Gate Status,link={uri-qg-status}]

= MorrS

MorrS - это виртуальный локальный магазин игр. 

== Функции

- MorrS дает возможность войти под именем разработчика, а также геймера. 
- Разработчик может добавить совю игру, обновлять ее, при необходимости удалить.
- Геймер, в свою очередь может добавить созданную разработчиком игру в свою библиотеку, удалить ее оттуда.
- Интерфейс и функционал программы будет соверщенствоваться по мере ее написания, все изменения будут отражены в этом Readme.
- Планируется добавление системы отзывав, распродаж, полное изменение системы входа и полное изменение визуальной части программы.

== Структура проета 

Проект разделен на следующие файлы:

- `dev_opt.cpp`
- `dev_opt.h`
- 'gam_opt.cpp'
- 'gam_opt.cpp.h'
- 'user_interfaces.cpp'
- 'user_interfaces.h'
- 'main.cpp'

== Ссылка на Sonar

https://sonarcloud.io/project/overview?id=Chawotto_MorrS
