name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        choco install qt6-base-dev
      
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH="C:/Qt/5.15.2/msvc2019_64"
        cmake --build .

    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        build-wrapper-win-x86-64 --out-dir bw-output cmake --build .
        sonar-scanner
